server:
  port: 8085

spring:
  data:
    mongodb:
      host:
      port:
      database:
  kafka:
    bootstrap-servers:
    consumer-vehicle-events:
      topic: 'vehicle.events'
      group-id: 'vehicle-events-listener-service'
      auto-offset-reset: 'earliest'
    consumer-vehicle-overspeed-events:
      topic: 'overspeed.vehicle.events'
      group-id: 'vehicle-overspeed-events-listener-service'
      auto-offset-reset: 'earliest'

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui-custom.html
  api-docs:
    path: /api-docs
